config/routes.rb
Rails.application.routes.draw do
  # resources :contacts
  resources :following_users
  resources :followers
  resources :bulletins
  resources :categories
  get "contact/index"
  match "contact/new", to: "contact#new", via: [ :get ]
  post "/submit_contact_form", to: "contact#create"
  resource :session
  resources :users
  resources :passwords, param: :token
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "follow_user", to: "users#follow_user", via: [ :post ]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user

  validates :follower_id, presence: true
  validates :follower_id, comparison: { other_than: :user_id }
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  before_action :set_follower, only: %i[ show edit update destroy ]

  # GET /followers or /followers.json
  def index
    # @followers = current_user.followers
  end

  # GET /followers/1 or /followers/1.json
  def show
  end

  # GET /followers/new
  def new
    @follower = Follower.new
  end

  # GET /followers/1/edit
  def edit
  end

  # POST /followers or /followers.json
  def create
    @follower = Follower.new(follower_params)

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: "Follower was successfully created." }
        format.json { render :show, status: :created, location: @follower }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /followers/1 or /followers/1.json
  def update
    respond_to do |format|
      if @follower.update(follower_params)
        format.html { redirect_to @follower, notice: "Follower was successfully updated." }
        format.json { render :show, status: :ok, location: @follower }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1 or /followers/1.json
  def destroy
    @follower.destroy!

    respond_to do |format|
      format.html { redirect_to followers_path, status: :see_other, notice: "Follower was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_follower
      @follower = Follower.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def follower_params
      params.expect(follower: [ :user_id, :follower_id ])
    end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_follower.html.erb
<div id="<%= dom_id follower %>">
  <p>
    <strong>User:</strong>
    <%= follower.user_id %>
  </p>

  <p>
    <strong>Follower:</strong>
    <%= follower.follower_id %>
  </p>

</div>

app/views/followers/_form.html.erb
<%= form_with(model: follower) do |form| %>
  <% if follower.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(follower.errors.count, "error") %> prohibited this follower from being saved:</h2>

      <ul>
        <% follower.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :follower_id, style: "display: block" %>
    <%= form.number_field :follower_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/followers/edit.html.erb
<% content_for :title, "Editing follower" %>

<h1>Editing follower</h1>

<%= render "form", follower: @follower %>

<br>

<div>
  <%= link_to "Show this follower", @follower %> |
  <%= link_to "Back to followers", followers_path %>
</div>

app/views/followers/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Followers" %>

<h1>Followers</h1>



<%= link_to "New follower", new_follower_path %>

app/views/followers/new.html.erb
<% content_for :title, "New follower" %>

<h1>New follower</h1>

<%= render "form", follower: @follower %>

<br>

<div>
  <%= link_to "Back to followers", followers_path %>
</div>

app/views/followers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @follower %>

<div>
  <%= link_to "Edit this follower", edit_follower_path(@follower) %> |
  <%= link_to "Back to followers", followers_path %>

  <%= button_to "Destroy this follower", @follower, method: :delete %>
</div>