config/routes.rb
Rails.application.routes.draw do
  # resources :contacts
  resources :following_users
  resources :followers
  resources :bulletins
  resources :categories
  get "contact/index"
  match "contact/new", to: "contact#new", via: [ :get ]
  post "/submit_contact_form", to: "contact#create"
  resource :session
  resources :users
  resources :passwords, param: :token
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  match "follow_user", to: "users#follow_user", via: [ :post ]
  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord
  has_one_attached :image

  scope :last_news, -> { select("bulletins.id, bulletins.title, bulletins.created_at, bulletins.source").order(created_at: :desc).limit(3) }
end

app/models/categories_tag.rb
class CategoriesTag < ApplicationRecord
  belongs_to :tag
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :posts
  has_one_attached :image do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 150, 150 ]
  end
  has_many :categories_tags
  has_many :tags, through: :categories_tags
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

end

app/models/comments_like.rb
class CommentsLike < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :mail, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user

  validates :follower_id, presence: true
  validates :follower_id, comparison: { other_than: :user_id }
end

app/models/following_user.rb
class FollowingUser < ApplicationRecord
  belongs_to :user

  validates :following_user_id, presence: true

  validates :user_id, comparison: { other_than: :following_user_id }
end

app/models/post.rb
class Post < ApplicationRecord
    has_rich_text :body
    has_many :comments
    has_and_belongs_to_many :categories
    has_and_belongs_to_many :categories_names,
                          -> { select("categories.id, categories.name") }, # Calificar con el nombre de la tabla
                          class_name: "Category",
                          join_table: "categories_posts", # Asegúrate que el nombre de la tabla de unión sea el correcto
                          association_foreign_key: "category_id",
                          foreign_key: "post_id"
    belongs_to :user
    has_one_attached :hero_image do |attachable|
        attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
      end

    accepts_nested_attributes_for :categories

    scope :related, -> { select("posts.id, posts.title, posts.created_at") }

    validates :title, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :categories_tags
  has_many :categories, through: :categories_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :avatar
  has_many :sessions, dependent: :destroy
  has_many :posts
  has_many :posts_titles, -> { select("posts.id, posts.title") }, class_name: "Post"
  has_many :comments
  has_many :followers, foreign_key: :follower_id
  has_many :followers_users, through: :followers, source: :user
  has_many :following_users, foreign_key: :following_user_id
  has_many :following_users_users, through: :following_users, source: :user

  validates_confirmation_of :password
  validates_presence_of :password_confirmation, if: -> { password.present? } # Para asegurar que se envíe si la contraseña se está estableciendo

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 100, 100 ]
  end
end

app/controllers/following_users_controller.rb
class FollowingUsersController < ApplicationController
  before_action :set_following_user, only: %i[ show edit update destroy ]

  # GET /following_users or /following_users.json
  def index
    @following_users = current_user.following_users_users
  end

  # GET /following_users/1 or /following_users/1.json
  def show
  end

  # GET /following_users/new
  def new
    @following_user = FollowingUser.new
  end

  # GET /following_users/1/edit
  def edit
  end

  # POST /following_users or /following_users.json
  def create
    @following_user = FollowingUser.new(following_user_params)

    respond_to do |format|
      if @following_user.save
        format.html { redirect_to @following_user, notice: "Following user was successfully created." }
        format.json { render :show, status: :created, location: @following_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @following_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /following_users/1 or /following_users/1.json
  def update
    respond_to do |format|
      if @following_user.update(following_user_params)
        format.html { redirect_to @following_user, notice: "Following user was successfully updated." }
        format.json { render :show, status: :ok, location: @following_user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @following_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /following_users/1 or /following_users/1.json
  def destroy
    @following_user.destroy!

    respond_to do |format|
      format.html { redirect_to following_users_path, status: :see_other, notice: "Following user was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_following_user
      @following_user = FollowingUser.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def following_user_params
      params.expect(following_user: [ :user_id, :following_user_id ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_related_posts
    Post.related.joins(:hero_image_attachment).includes(:hero_image_attachment).last(3)
  end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/following_users_helper.rb
module FollowingUsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/following_users/_following_user.html.erb
<div id="<%= dom_id following_user %>">
  <p>
    <strong>User:</strong>
    <%= following_user.user_id %>
  </p>

  <p>
    <strong>Following user:</strong>
    <%= following_user.following_user_id %>
  </p>

</div>

app/views/following_users/_form.html.erb
<%= form_with(model: following_user) do |form| %>
  <% if following_user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(following_user.errors.count, "error") %> prohibited this following_user from being saved:</h2>

      <ul>
        <% following_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :following_user_id, style: "display: block" %>
    <%= form.number_field :following_user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/following_users/edit.html.erb
<% content_for :title, "Editing following user" %>

<h1>Editing following user</h1>

<%= render "form", following_user: @following_user %>

<br>

<div>
  <%= link_to "Show this following user", @following_user %> |
  <%= link_to "Back to following users", following_users_path %>
</div>

app/views/following_users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Following users" %>

<h1>Following users</h1>

<div id="following_users">
  <% @following_users.each do |following_user| %>
    <%= following_user.email_address %>
    <%= following_user.presentation %>
    <p>
      <%= link_to "Show this following user", following_user %>
    </p>
  <% end %>
</div>

<%= link_to "New following user", new_following_user_path %>

app/views/following_users/new.html.erb
<% content_for :title, "New following user" %>

<h1>New following user</h1>

<%= render "form", following_user: @following_user %>

<br>

<div>
  <%= link_to "Back to following users", following_users_path %>
</div>

app/views/following_users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @following_user %>

<div>
  <%= link_to "Edit this following user", edit_following_user_path(@following_user) %> |
  <%= link_to "Back to following users", following_users_path %>

  <%= button_to "Destroy this following user", @following_user, method: :delete %>
</div>